/*
 * GLOBAL_DEFINES.h
 *
 *  Created on: Oct 3, 2020
 *      Author: aleca
 */

#ifndef APPLICATION_GLOBAL_DEFINES_H_
#define APPLICATION_GLOBAL_DEFINES_H_

#define EVENT_ENABLE_ADVERTISEMENT 69
#define EVENT_DISABLE_ADVERTISEMENT 70
#define EVENT_UPDATE_BRICKID 71
#define EVENT_READ_ID_TO_FLASH 72
#define EVENT_WRITE_ID_TO_FLASH 73

#define BRICK_TYPE_4x2 3001
#define BRICK_TYPE_2x2 3003
#define BRICK_TYPE_4x4_CORNER 702

#define BRICK_TYPE BRICK_TYPE_4x2

#define BRICK_ID_FLASH_NV_ID 0x81


#endif /* APPLICATION_GLOBAL_DEFINES_H_ */
